Stage1 completed
MaksimLakatkouOld/jet-start pull request #1
Opened 2021-10-21 09:51 UTC by MaksimLakatkouOld

Stage1 completed

2021-10-21 16:23 UTC, igr-ik commented on sources/views/data.js
> +							const activitiesSelectedDueDate = this.$getDataActivities().getItem(row).DueDate;
Пять строк подряд, ты получаешь таблицу, у таблицы берешь некую запись, и все для того чтобы взять одно свойство и сохранить в константу? Пять раз подряд! Пять раз ты заставляешь JS проделывать одну и ту же работу. Тебя самого это не смущает? )

Метод getItem возвращает объект записи, достаточно получить его один раз и проделывать с ним все что угодно.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/data.js
> +							const activitiesSelectedDate = webix.Date.datePart(parseSelectedDueDate);
Не совсем понимаю для чего нужны все эти преобразования с датами.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/data.js
> +								activitiesSelectedTime
Чтобы не передавать такое большое количество параметров, можно было передать это все объектом.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/data.js
> +		this._jetPopupEdit = this.ui(PopupEdit);
Названия _jetPopup и _jetPopupEdit, как и PopupAdd, и PopupEdit мне вообще не о чем не говорят. Не понятно что этот попап добавляет и что редактирует.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/data.js
> +			});
Вместо такого количества параметров, ты мог передать вот точно такой же объект, и вкинуть его в activitiesCollection.add

2021-10-21 16:23 UTC, igr-ik commented on sources/views/data.js
> +			});
Здесь тоже самое, слишком большое количество параметров, можно обойтись объектом.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/start.js
> +						template: "<div class='table_contact_info'><div class='cell_contact_info div_contact_info ico-user_male_circle'></div><div class='cell_contact_info'><div class='div_firstLastName'>#FirstName# #
Для удобства чтения, всю эту html структуру, можно вложить в строковый шаблон, с переносами строк и табуляцией.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/start.js
> +													template: "<div class='photo'><div class='photo_in'><h1>Photo</h1></div></div>",
Это тоже, можно сделать в строковом шаблоне.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/start.js
> +						{
Всю эту структуру, можно обернуть в view "form", вместо темплейтов, кроме темплейта с фото, можно использовать view "label". Каждому лэйблу, задать name и названием нужного свойства.

И тогда, в событии onAfterSelect, не придется обращаться в каждой вьюшке, и устанавливать значения, достаточно будет обратиться к форме и в setValues кинуть весь объект, и форма уже сама засетит каждому лэйблу значения. Темплейт с фото, оставить как есть.

Почему сработает view "form"!? В своем внутреннем строении, форма устанавливает и получает значения у тех вью, у которые есть два метода, setValue и getValue. Не путай с setValues и getValues. С view "label" это сработает, так как у него есть эти два метода - setValue и getValue. А у view "template" - setValues и getValues, поэтому с ним это не сработает.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/top.js
> +					const menuSelectedItem = this.$getTopMenu().getItem(menuSelectedItemId);
Правило такое, если два и более раза обращаешься к одному и тому же элементу, например this.$getTopMenu(), сохрани есть в константу и дальше с ней работай.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/windows/popupAddEdit.js
> +										const newActivitiesContactID = this.getFormActivitiesValues().ContactID;
Зачем каждый раз дергать this.getFormActivitiesValues()? Получи один раз объект со значениями, сохрани констану и работай дальше с ним, вытаскивай нужные свойства. И этот же объект можно передать в событие "activitiesItemAdd", как один параметр.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/windows/popupAddEdit.js
> +									const newActivitiesContactID = this.getFormActivitiesValues().ContactID;
Здесь такая же история с получением значений из формы, как выше.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/windows/popupAddEdit.js
> +			) => {
Получал бы здесь объект одним параметром, проще было бы в setValues его вкинуть.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/windows/popupAdd.js
> +export default class PopupEdit extends PopupAddEdit {
Когда копипастишь, следи за названиями классов, PopupEdit у тебя уже два класса, но файлах с разными названиями.

2021-10-21 16:23 UTC, igr-ik commented on sources/views/windows/popupAdd.js
> +	}
Разделить логику на добавления и редактирования в разные классы, и унаследовать их от базового класса, это хорошая идея, только воспользовался ты этим не очень красиво.
Используй здесь полиморфизм. Создай полиморфные методы в базовом классе, с пустой реализацией, и в этом же классе вызывай их где нужно. Потом в дочерних классах реализуй логику этим методам.

На пример, можешь создать метод в базом классе
getHeader() {}

в дочернем реализовать его
getHeader() {
return {
						css: "add_activity",
						template: "Add activity",
						height: 50
					};
}

и по такому примеру другие полиморфные методы можно реализовать.

2021-10-22 14:11 UTC, kullias requested changes

2021-10-22 14:11 UTC, kullias commented on sources/views/data.js
> +							const activitiesSelectedDate = webix.Date.datePart(parseSelectedDueDate);
тут вообще можно не доставать из объекта проперти, а отправить в параметр весь объект активити

кроме того, если и извлекать дату и время из одного значения с датой, то лучше не методами локализации,а  методами webix.Date. но и это можно не делать. можно просто скопировать дату в поля для дейтпикера и таймпикера и так и засеттить. максимум от даты для дейтпикера можно отрезать время (webix.Date.dayStart - он еще и дату скопирует)

2021-10-22 14:11 UTC, kullias commented on sources/views/data.js
> +							sort: "string"
неправильно работает для дат. у нас есть сортировщик для дат
![Screenshot from 2021-10-22 16-21-58](https://user-images.githubusercontent.com/31205423/138460804-e28cb9c1-5a9f-40b7-8a72-7d286bf8286e.png)

2021-10-22 14:11 UTC, kullias commented on sources/views/data.js
> +								{content: "dateRangeFilter"}
кажется не работает как надо
у меня есть событие на 22 октября 00:00, а фильтр его почему-то не показывает

2021-10-22 14:11 UTC, kullias commented on sources/views/data.js
> +							sort: "string"
неправильно работает, потому что видимо сравнивает айдишки
у нас есть сортировщик text если надо сравнивать отображаемый в колонке текст

2021-10-22 14:11 UTC, kullias commented on sources/views/data.js
> +							sort: "string"
то же что с типами активити

2021-10-22 14:11 UTC, kullias commented on sources/views/windows/popupAddEdit.js
> +			view: "popup",
лучше сделать модальным окном

2021-10-22 14:11 UTC, kullias commented on sources/views/windows/popupAddEdit.js
> +									this.$getPopupFormActivities().hide();
если открыть форму на редактирование, нажать cancel, а потом открыть форму для add, форма уже заполнена данными
что надо делать:
- перед закрытием чистить форму, чистить валидацию

2021-10-22 14:11 UTC, kullias commented on sources/views/start.js
> +						onAfterSelect: (row) => {
касается всех классов:
функции из config() стоит выносить в методы класса, а то конфиг становится огромным и сложно читать

2021-10-22 14:11 UTC, kullias commented on sources/views/windows/popupAddEdit.js
> +								click: () => {
код обработчиков этих кнопок почти один в один
стоит вынести в 1 метод класса

2021-10-22 14:11 UTC, kullias commented on sources/views/data.js
> +							this.app.callEvent("activitiesItemEdit", [
у окна есть метод для show
можно вообще избавиться от события этого
почему бы не передавать объект в метод? он будет и окно показывать, и перед этим форму в окне нужными данными заполнять

2021-10-22 14:11 UTC, kullias commented on sources/views/data.js
> +							const activitiesSelectedDate = webix.Date.datePart(parseSelectedDueDate);
плюс того, чтобы просто объект из коллекции передавать окну - там будет айди
у формы, которую заполнили для нового события, айди среди ее values не будет
это можно использовать для того, чтобы отличать одну операцию от другой: есть айди - значит это апдейт
из чего получается, что кнопку в той форме можно оставить одну, метод будет один, который по наличию айди будет делать или апдейт, или эдд
остается только кнопке этой менять лейбл
и хедеру формы

2021-10-22 14:11 UTC, kullias commented on sources/myapp.js
хорошая идея - обрабатывать ошибки error:resolve
поскольку структура приложения строится на основе урла, а урл легко поменять и сделать опечатку, хорошо бы перенаправлять с неправильного урла на какую-то стартовую страницу (например top/start)

2021-10-22 14:11 UTC, kullias commented on sources/views/toolbarAddActivity.js
> +		this._jetPopupAdd = this.ui(PopupAdd);
у тебя в итоге аж три попапа в приложении создается, не очень хорошо
пожалуй, этому классу стоит посылать событие в data.js, чтобы тот открывал свой попап

еще штука с наследованием попапов от базового класса дело хорошее, но между этими попапами разница слишком маленькая, мне кажется. и можно было бы оставить один класс, а перед показом просто менять лейблы на хедере и кнопке. ну а тип операции определять по наличию айди в данных, которые засеттили в форму
таким образом останется 1 попап (ну и опять же, лучше чтобы это было модальным окном)

2021-10-24 23:01 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +							const activitiesSelectedDueDate = this.$getDataActivities().getItem(row).DueDate;
исправил

2021-10-24 23:01 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +							const activitiesSelectedDate = webix.Date.datePart(parseSelectedDueDate);
да Игорь, не нужны, исправил.
Настя, проработал вопрос с передачей объекта с id.

2021-10-24 23:01 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +								activitiesSelectedTime
исправил

2021-10-24 23:01 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +		this._jetPopupEdit = this.ui(PopupEdit);
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +			});
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +			});
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +						template: "<div class='table_contact_info'><div class='cell_contact_info div_contact_info ico-user_male_circle'></div><div class='cell_contact_info'><div class='div_firstLastName'>#FirstName# #
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +													template: "<div class='photo'><div class='photo_in'><h1>Photo</h1></div></div>",
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +						{
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/top.js
> +					const menuSelectedItem = this.$getTopMenu().getItem(menuSelectedItemId);
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEdit.js
> +										const newActivitiesContactID = this.getFormActivitiesValues().ContactID;
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEdit.js
> +									const newActivitiesContactID = this.getFormActivitiesValues().ContactID;
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEdit.js
> +			) => {
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAdd.js
> +export default class PopupEdit extends PopupAddEdit {
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAdd.js
> +	}
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +							sort: "string"
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +								{content: "dateRangeFilter"}
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +							sort: "string"
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +							sort: "string"
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEdit.js
> +			view: "popup",
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEdit.js
> +									this.$getPopupFormActivities().hide();
сделал

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +						onAfterSelect: (row) => {
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEdit.js
> +								click: () => {
исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +							this.app.callEvent("activitiesItemEdit", [
это очень круто) исправил

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/myapp.js
сделал, спасибо, удобная штука

2021-10-24 23:02 UTC, MaksimLakatkouOld commented on sources/views/toolbarAddActivity.js
> +		this._jetPopupAdd = this.ui(PopupAdd);
оставил два попапа

2021-10-25 12:05 UTC, kullias requested changes

2021-10-25 12:05 UTC, kullias commented on sources/models/activities.js
> +		$init: (obj) => {
если надо применять изменения на инит и update, то надо использовать один ключ - $change

2021-10-25 12:05 UTC, kullias commented on sources/views/data.js
> +						on_click_edit: (e, row) => { this.showFormEditActivities(e, row); },
ты в обоих методах не используешь параметр e, значит не надо его передавать туда (нет необходимости)

2021-10-25 12:05 UTC, kullias commented on sources/views/data.js
> +			if (formActivitiesValues.id) {
в if-else очень много одинакового кода
предлагаю вынести его до ветвления (и вообще все из обработчика вынести в метод класса)

2021-10-25 12:05 UTC, kullias commented on sources/views/start.js
> +													autowidth: true
в итоге ширина лейбла подстраивается под длину слов FirstName и LastName
и если потом длина имен сильно отличается (если не вызывать после setValues resize для лейблов https://snippet.webix.com/b366pshx):
![Selection_999(334)](https://user-images.githubusercontent.com/31205423/138689069-928cdf5f-dba1-48a0-83fd-188d88a112e7.png)

я б лучше сделала один лейбл для имени и фамилии

еще чтобы undefined не светились в интерфейсе, добавила бы какие-то минимальные плейсхолдеры для пустых значений в духе (no skype)

и еще статус не должен как его айдишка отображаться (не 7, а текст из Value)

2021-10-25 12:05 UTC, kullias commented on sources/views/start.js
> +															template: "<span class='ico-location'>location</span>",
#location# или если будешь делать плейсхолдер obj.location и функция

2021-10-25 12:05 UTC, kullias commented on sources/views/start.js
> +					view: "form",
на 2 стейдже придется разбить этот модуль на лист и форму (и ее тоже придется разбить на пару модулей, потому что там будут еще другие компоненты)
можно сделать это уже сейчас, но можно и на 2 стейдже
когда будешь разбивать, нужно будет обеспечить коммуникацию между листом и формой другим образом (скорее всего параметр урла)

2021-10-25 12:05 UTC, kullias commented on sources/views/top.js
> +					const menuSelectedItemId = topMenu.getSelectedId();
в onAfterSelect приходит параметр id
и функцию тоже стоит вынести в метод класса, потому что метод config уже очень длинный

2021-10-25 12:05 UTC, kullias commented on sources/views/windows/popupAddEditActivities.js
> +								view: "datepicker",
тут таймпикер остался, надо убрать

2021-10-25 12:05 UTC, kullias commented on sources/views/windows/popupAddEditActivities.js
> +	showFormAddEditActivities() {
имя метода смущает
метод делает валидацию и вызывает ивент, который передает данные, которые надо сохранить
может как-то так его и назвать - saveChanges

2021-10-25 12:05 UTC, kullias commented on sources/views/windows/popupAddEditActivities.js
> +			this.$getFormActivities().setValues(activitiesSelectedItemValues);
я б не извлекала нужные проперти, а просто докинула бы в activitiesSelectedItem дату и время и засеттила так

2021-10-25 12:11 UTC, igr-ik commented on sources/models/activities.js
> +			if (obj.DueDate) obj.DueDateObject = webix.i18n.parseFormatDate(obj.DueDate);
1) Дубликат кода
2) Любишь ты все в одну строку лепить, для читаемости кода это плохо

2021-10-25 12:11 UTC, igr-ik commented on sources/views/data.js
> +				const activitiesContactID = formActivitiesValues.ContactID;
Не понимаю, зачем вытягивать из объекта в значения каких-то свойств, сохранять их в переменные, а потом снова компоновать в объект под такими же названиями свойств...

formActivitiesValues - это уже объект, не нужно из него ничего лишнего вытягивать, кроме свойств даты и времени. достаточно просто проделать эти действия:
```
const activitiesDate = formatDate(formActivitiesValues.date);
const activitiesTime = formatTime(formActivitiesValues.time);
formActivitiesValues.DueDate = `${activitiesDate} ${activitiesTime}`;
```

потом:
```
const activitiesSelectedItemId = this.$getDataActivities().getSelectedId();
activitiesCollection.updateItem(activitiesSelectedItemId, formActivitiesValues);
```

Если хочешь создать копию объекта (если конечно, в этом есть смысл), можно сделать так:
```
const updatedActivitiesItemValues = {
    ...formActivitiesValues,
    DueDate: activitiesDueDate
};
```

2021-10-25 12:11 UTC, igr-ik commented on sources/views/data.js
> +				const formatTime = webix.Date.dateToStr("%H:%i");
Две строчки дубликаты, часто в коде используешь.
Можешь вынести их в методы, а еще лучше в отдельный файл, например helpers.js, создать там функции:
formatDate
formatTime

Потом импортируй где нужно и используй эти функции

2021-10-25 12:11 UTC, igr-ik commented on sources/views/data.js
> +				activitiesCollection.add(newActivitiesItemValues);
В этом блоке else, все то же самое что я описывал выше

2021-10-25 12:11 UTC, igr-ik commented on sources/styles/app.css
> +.webix_el_datepicker .webix_inp_static, .webix_el_combo input, .webix_el_textarea textarea {
Пора бы тебе запомнить, что писать код в одну строку, это очень плохо для читаемости кода, как в JS, так в CSS и HTML. На боевом проекте работать будешь не один, и вряд ли команда по достоинству оценит такой код. Да и тебе самому же, потом в будущем будет легче читать.

После запятой, выноси селекторы на новую строку:
```
.webix_el_datepicker .webix_inp_static,
.webix_el_combo input,
.webix_el_textarea textarea
```

Везде это делай, даже с такими коротенькими селекторами:
```
.add_activity,
.edit_activity
```

2021-10-25 12:11 UTC, igr-ik commented on sources/views/start.js
> +									<div class='div_company'>#Company#</div>
Что означает div в начале названия класса? А если в будущем, тег div нужно будет переделать в span, имя класса тоже будешь переделывать на "span_company"?

Советую почитать про методологию БЭМ. Там разъясняют как лучше делать именования классов.

Я бы все это сделал так:
Класс компоненту дал такой
```
{
    ...
    css: "user-contacts",
    ...
}
```
далее template:
```
{
    template: `
        <div class='user-contacts__item'>
            <div class='user-contacts__photo'></div>
            <div class='user-contacts__details'>
                <div class='user-contacts__fullname'>#FirstName# #LastName#</div>
                <div class='user-contacts__company'>#Company#</div>
            </div>
        </div>
    `
}
```

2021-10-25 12:11 UTC, igr-ik commented on sources/views/start.js
> +																</div>
Темплейт для фото, а где само фото?

2021-10-25 12:11 UTC, igr-ik commented on sources/views/windows/popupAddActivities.js
> +		};
Здесь можно просто текст возвращать, чтобы не приходилось к свойству объекта обращаться.

```
getActivitiesAddSaveButtonValue() {
    return "Add";
}
```

2021-10-25 12:11 UTC, igr-ik commented on sources/views/windows/popupAddEditActivities.js
> +								click: () => { this.showFormAddEditActivities(); }
Когда при клике, стрелочная функция вызывает только одну функцию, то фигурные скобки не нужны:
`click: () => this.showFormAddEditActivities()`

2021-10-25 12:11 UTC, igr-ik commented on sources/views/windows/popupAddEditActivities.js
> +	showFormAddEditActivities() {
Этому методу больше подходит названия submitForm()
В названии show... имеется ввиду что ты что-то показываешь, но в этом методе ничего не показывается

2021-10-25 12:11 UTC, igr-ik commented on sources/views/windows/popupAddEditActivities.js
> +			this.$getPopupFormActivities().hide();
Три строчки дубликаты, они встречаются в hideFormAddEditActivities методе, ты можешь просто вызвать его здесь, вместо этих трех строк.

2021-10-25 12:11 UTC, igr-ik commented on sources/views/windows/popupAddEditActivities.js
> +			const activitiesSelectedItemTime = new Date(activitiesSelectedItemDueDateObject);
DueDateObject уже содержит объект даты, преобразование ты делал в DataCollection, в схеме:
```
$init: (obj) => {
    if (obj.DueDate) obj.DueDateObject = webix.i18n.parseFormatDate(obj.DueDate);
}
```

2021-10-25 12:11 UTC, igr-ik commented on sources/views/windows/popupAddEditActivities.js
> +			this.$getFormActivities().setValues(activitiesSelectedItemValues);
Все это можно сделать намного проще:
```
showWindow(activitiesSelectedItem) {
    if (activitiesSelectedItem) {
        const activitieDueDate = activitiesSelectedItem.DueDateObject;
        activitiesSelectedItem.date = activitieDueDate;
        activitiesSelectedItem.time = activitieDueDate;
        this.$getFormActivities().setValues(activitiesSelectedItem);
    }

    this.$getPopupFormActivities().show();
}
```

2021-10-25 12:11 UTC, igr-ik commented on sources/views/windows/popupAddEditActivities.js
> +		const formActivities = this.getRoot();
Зачем обращаешься к this.getRoot(), если у тебя есть метод $getPopupFormActivities() ?

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/models/activities.js
> +		$init: (obj) => {
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +						on_click_edit: (e, row) => { this.showFormEditActivities(e, row); },
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +			if (formActivitiesValues.id) {
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +													autowidth: true
status исправил, а template договорились что посмотришь.

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +															template: "<span class='ico-location'>location</span>",
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +					view: "form",
да, смотрел stage2, понял что там надо будет разбить модуль, сделаю на следующем этапе

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/top.js
> +					const menuSelectedItemId = topMenu.getSelectedId();
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +								view: "datepicker",
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +	showFormAddEditActivities() {
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +			this.$getFormActivities().setValues(activitiesSelectedItemValues);
исправил

2021-10-26 12:02 UTC, MaksimLakatkouOld commented on sources/models/activities.js
> +			if (obj.DueDate) obj.DueDateObject = webix.i18n.parseFormatDate(obj.DueDate);
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +				const activitiesContactID = formActivitiesValues.ContactID;
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +				const formatTime = webix.Date.dateToStr("%H:%i");
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +				activitiesCollection.add(newActivitiesItemValues);
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/styles/app.css
> +.webix_el_datepicker .webix_inp_static, .webix_el_combo input, .webix_el_textarea textarea {
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +									<div class='div_company'>#Company#</div>
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +																</div>
с Настей договорились пока просто закрашенный прямоугольник)

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddActivities.js
> +		};
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +								click: () => { this.showFormAddEditActivities(); }
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +	showFormAddEditActivities() {
исправил, назвал saveChanges()

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +			this.$getPopupFormActivities().hide();
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +			const activitiesSelectedItemTime = new Date(activitiesSelectedItemDueDateObject);
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +			this.$getFormActivities().setValues(activitiesSelectedItemValues);
исправил

2021-10-26 12:03 UTC, MaksimLakatkouOld commented on sources/views/windows/popupAddEditActivities.js
> +		const formActivities = this.getRoot();
исправил

2021-10-26 13:15 UTC, igr-ik commented on sources/models/activities.js
> +			if (obj.DueDate) obj.DueDateObject = webix.i18n.parseFormatDate(obj.DueDate);
Дублирование убрал, но код как был в одну строку, так и остался
```
if (obj.DueDate)
    obj.DueDateObject = webix.i18n.parseFormatDate(obj.DueDate);
```

2021-10-26 13:15 UTC, igr-ik commented on sources/views/data.js
> +			const activitiesSelectedItemId = this.$getDataActivities().getSelectedId();
У тебя уже есть id активити которое нужно обновить - formActivitiesValues.id, нет смысла у компонента запрашивать текущую выделенную активити.

2021-10-26 13:15 UTC, igr-ik commented on sources/views/data.js
> +				(formActivitiesValues)
Круглые скобки лишние.

2021-10-26 18:05 UTC, kullias commented on sources/views/data.js
> +					id: "dataActivities",
глобальные айди в джете зло, поскольку если ты используешь этот класс 2+ раз, на странице будет 2+ компонент с одной айдишкой. баги в таких случаях могут быть крайне загадочными и досадными, а могут вообще поломать все
лучше просто никогда-никогда в джете не задавать компонентам глобальные айди
лучше использовать локальные айди + this.$$ для доступа к компонентам по локальным айди

2021-10-26 18:05 UTC, kullias commented on sources/views/start.js
> +								{
лучше поменять лейаут формы и сделать:
- ряд с именем и кнопками
- ряд со всем остальным, где они в колонки (и внутри в ряды) - и это 1 темплейт, не форма, из-за невозможности использовать лейблы для чего-то кроме показа простого текста без верстки (подробности в ЛС  в скайпе)

иначе особенно на маленьких экранах беда. кнопки занимают почти треть места в форме, но не используют это место, а лейблы сбиваются в кучу

2021-10-26 18:05 UTC, kullias commented on sources/views/start.js
> +		listContactItem.status = status.Value;
в данных может быть несуществующий статус (после тестирования на 3 стейдже)
listContactItem.status = status ? status.Value : "";

2021-10-26 18:05 UTC, kullias commented on sources/views/start.js
> +								<div class='user-contacts__photo ico-user_male_circle'></div>
стоит выровнять имена по одной линии (горизонтально они кто как начинаются)
![Selection_999(348)](https://user-images.githubusercontent.com/31205423/138934146-b2c5b0d2-b4fc-423d-9aa5-5b222f4e0579.png)

2021-10-26 21:38 UTC, MaksimLakatkouOld commented on sources/models/activities.js
> +			if (obj.DueDate) obj.DueDateObject = webix.i18n.parseFormatDate(obj.DueDate);
линтер не пропускает и автоматически переписывает в одну строку: Expected no linebreak before this statement  nonblock-statement-body-position

2021-10-26 21:38 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +			const activitiesSelectedItemId = this.$getDataActivities().getSelectedId();
исправил

2021-10-26 21:38 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +				(formActivitiesValues)
исправил

2021-10-26 21:38 UTC, MaksimLakatkouOld commented on sources/views/data.js
> +					id: "dataActivities",
да, понимаю, пропустил),
исправил

2021-10-26 21:38 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +								{
ряд с именем и кнопками исправил,
замена label на template будет выполнена на stage2

2021-10-26 21:38 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +		listContactItem.status = status.Value;
исправил

2021-10-26 21:38 UTC, MaksimLakatkouOld commented on sources/views/start.js
> +								<div class='user-contacts__photo ico-user_male_circle'></div>
исправил

2021-10-27 07:03 UTC, igr-ik approved these changes

2021-10-27 08:57 UTC, kullias approved these changes

2021-10-27 08:57 UTC, merged